<?php

namespace Lpmr\AppBundle\Repository;

/**
 * categorie_elementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categorie_elementRepository extends \Doctrine\ORM\EntityRepository
{
}
