lpmr_user_groupe:
    resource: "@LpmrUserBundle/Resources/config/routing/groupe.yml"
    prefix:   /groupe


lpmr_user_etudiant:
    resource: "@LpmrUserBundle/Resources/config/routing/etudiant.yml"
    prefix:   /etudiant



lpmr_user_homepage:
    resource: "@LpmrUserBundle/Resources/config/routing/groupe.yml"
    prefix:   /
    
