groupe_index:
    path:     /index
    defaults: { _controller: "LpmrUserBundle:Groupe:index" }
    methods:  GET

groupe_show:
    path:     /{id}/show
    defaults: { _controller: "LpmrUserBundle:Groupe:show" }
    methods:  GET

groupe_new:
    path:     /new
    defaults: { _controller: "LpmrUserBundle:Groupe:new" }
    methods:  [GET, POST]

groupe_edit:
    path:     /{id}/edit
    defaults: { _controller: "LpmrUserBundle:Groupe:edit" }
    methods:  [GET, POST]

groupe_delete:
    path:     /{id}/delete
    defaults: { _controller: "LpmrUserBundle:Groupe:delete" }
    methods:  DELETE

groupe_json:
    path:     /api/login
    defaults: { _controller: "LpmrUserBundle:Groupe:getOneGroupe" }
    methods:  [POST]

groupe_home:
    path:   /
    defaults: { _controller: "LpmrUserBundle:Groupe:home" }
