lpmr_user:
    resource: "@LpmrUserBundle/Resources/config/routing.yml"
    prefix:   /

lpmr_app:
    resource: "@LpmrAppBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"