lpmr_app_homepage:
    path:     /
    defaults: { _controller: LpmrAppBundle:Default:index }

lpmr_app_scenario:
    resource: "@LpmrAppBundle/Resources/config/routing/scenario.yml"
    prefix:   /scenario
    
lpmr_app_element:
    resource: "@LpmrAppBundle/Resources/config/routing/element.yml"
    prefix:   /element