<?php

namespace Lpmr\UserBundle\Repository;

/**
 * GroupeElementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeElementsRepository extends \Doctrine\ORM\EntityRepository
{
}
